favorite_books/book_app/urls.py
from django.urls import path
from . import views

app_name = 'book'
urlpatterns = [
    path("", views.main, name='main'),
    path("add_book",views.add_book,name='add_book'),
    path("add_favorite/<int:book_id>",views.add_favorite,name="add_favorite"),
    path("edit_book/<int:book_id>",views.edit_book,name='edit_book'),
    path("delete_book/<int:book_id>",views.delete_book,name='delete_book'),
    path("view_book/<int:book_id>",views.view_book,name='view_book'),
    path("un_favorite/<int:book_id>",views.un_favorite,name="un_favorite"),
    path("update_book/<int:book_id>",views.update_book,name='update_book')
]

favorite_books/favorite_books/urls.py
from django.urls import path,include

urlpatterns = [
    path('', include('login_registration_app.urls', namespace='user')),
    path('book', include('book_app.urls', namespace='book')),]
 

favorite_books/login_registration_app/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path("", views.index, name='main'),
    path("register", views.register, name='register'),
    path("login", views.login, name='login'),
    path("success", views.success, name='success'),
    path("logout", views.logout, name='logout'),
]

favorite_books/book_app/models.py
from django.db import models

# Create your models here.
from login_registration_app.models import User
# class User(models.Model):
#     first_name = models.CharField(max_length=255)
#     last_name = models.CharField(max_length=255)
#   # liked_books = a list of books a given user likes
#   # books_uploaded = a list of books uploaded by a given user   
class BookManager(models.Manager):
    
    def bookValidator(self, postData):
        err={}
        title = postData.get('title')
        desc  = postData.get('desc')
        if not title:
            err['title_required'] = 'Please enter the title.'
        if len(desc) < 5:
            err['description_length'] = 'Description must be at least 5 characters.' 
        return err           


# class usser :
#     list of liked_books
#     list of books_uploaded 


class Book(models.Model):
    title = models.CharField(max_length=255)
    uploaded_by = models.ForeignKey(User, related_name = "books_uploaded", on_delete = models.CASCADE) 
    users_who_like = models.ManyToManyField(User, related_name = "liked_books") 
    desc=models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = BookManager()

favorite_books/book_app/views.py
from django.shortcuts import render,redirect
from .models import *
from django.contrib import messages
def main(request):
    id=request.session['user_id']
    user=User.objects.get(id=id)
    context={
      "logged_user":user,
      "all_books":Book.objects.all(),
    }
    return render(request,"main.html",context)

def add_book(request):
    errors=Book.objects.bookValidator(request.POST)
    if request.method == 'POST':
        if len(errors) > 0:
            for key,value in errors.items():
                messages.error(request,value)
                return redirect('book:main')
        else:
            user =User.objects.get(id=request.session['user_id'])
            fav_book= Book.objects.create(title=request.POST['title'],desc=request.POST['desc'],uploaded_by=user)
            fav_book.users_who_like.add(user)
            return redirect('book:main')
        
def add_favorite(request,book_id):
    user =User.objects.get(id=request.session['user_id'])
    fav_book=Book.objects.get(id=book_id) 
    fav_book.users_who_like.add(user)
    print(f"{book_id}")
    return redirect('book:main') 

def un_favorite(request,book_id):
    user =User.objects.get(id=request.session['user_id'])
    fav_book=Book.objects.get(id=book_id) 
    fav_book.users_who_like.remove(user)
    print(f"{book_id}")
    return redirect('book:main')

     
def edit_book(request,book_id):
    id=request.session['user_id']
    user=User.objects.get(id=id)
    book=Book.objects.get(id=book_id)
    context={
      "logged_user":user,
      "liked_user": book.users_who_like.all(),
      "book" :book
    }    
    return render(request,"edit_book.html",context) 
        
           
def view_book(request,book_id):
    id=request.session['user_id']
    user=User.objects.get(id=id)
    book=Book.objects.get(id=book_id)
    context={
      "logged_user":user,
      "book" :book,
      "liked_user":book.users_who_like.all()
    } 
    
    return render(request,"view_book.html",context) 

def delete_book(request,book_id):
        id=request.session['user_id']
        user=User.objects.get(id=id)
        book=Book.objects.get(id=book_id)
        book.delete()
        messages.success(request, "Delete Book successfully!")
        return redirect('book:main')

def update_book(request,book_id):
    if request.method == 'POST':
        id=request.session['user_id']
        user=User.objects.get(id=id)
        book=Book.objects.get(id=book_id)
        book.title = request.POST['title']
        book.desc = request.POST['desc']
        book.save()
        messages.success(request, "Book updated successfully!")
    return redirect('book:edit_book',book_id=book_id) 
 

favorite_books/book_app/templates/edit_book.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Book</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">

</head>

<body>
    <div class="container py-4">
        <div class="d-flex justify-content-between align-items-center">
            <h3> Welcome {{logged_user.first_name}}</h3>
            <a href="{% url 'user:logout' %}" class="link-opacity-100">Logout</a>
        </div>
        <div class="row">
            <div class="col-md-6">
                <form action="{% url 'book:update_book' book.id %}" method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="title" class="form-label">Title</label>
                        <input class="form-control" type="text" id="title" name="title" value="{{book.title}}" />
                    </div>
                    <p>Added by :{{book.uploaded_by.first_name}} {{book.uploaded_by.Last_name}}</p>
                    <p>Added on :{{book.created_at}}</p>
                    <p>Last updated on :{{book.updated_at}}</p>
                    <div class="mb-3">
                        <label for="desc" class="form-label">Description</label>
                        <textarea class="form-control" id="desc" name="desc" rows="3"> {{book.desc}}</textarea>
                    </div>
                    <div>
                        <input type="submit" class="btn btn-success" value="Edit"></input>
                        <a href="{% url 'book:delete_book' book.id %}" class="btn btn-danger">Delete</a>
                    </div>
                </form>
            </div>
            <div class="col-md-6">
                <h4>User Who like This Book</h4>
                <ul>
                    {% for user in liked_user %}
                    <div>
                        <h5 style="display: inline;"> {{ user.first_name }} {{ user.last_name }} </h5>
                        {% if logged_user == user %}
                        <a href="{% url 'book:un_favorite' book.id  %}"> un favorite</a>
                        {% endif %}
                    </div>
                    {% endfor %}
                </ul>
            </div>
        </div>


        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show mt-3" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
        {% endif %}

    </div>
</body>
    <script>
        setTimeout(function () {
            document.querySelectorAll(".alert").forEach(function (alert) {
                alert.classList.add("fade");
                alert.classList.remove("show");
                setTimeout(() => alert.remove(), 500);
            });
        }, 3000);
    </script>
</html>

favorite_books/book_app/templates/main.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Favorite Books </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">

</head>

<body>
    <div class="container py-4">
        <div class="d-flex justify-content-between align-items-center">
            <h3> Welcome {{logged_user.first_name}}</h3>
            <a href="{% url 'user:logout' %}" class="link-opacity-100">Logout</a>
        </div>
        <div class="row mt-3">
            <div class="col-md-6">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h3 class="card-title mb-4 text-center">Add a Favorite Books</h3>
                        <form action="{% url 'book:add_book' %}" method="post">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="title" class="form-label">Title</label>
                                <input class="form-control" type="text" id="title" name="title" />
                            </div>
                            <div class="mb-3">
                                <label for="desc" class="form-label">Description</label>
                                <textarea class="form-control" id="desc" name="desc" rows="3"> </textarea>
                            </div>
                            <div>
                                <input type="submit" class="btn btn-success" value="Add"></input>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <h1>All Books</h1>
                {% for book in all_books %}
                <!-- single user 1 to many -->
                {% if logged_user == book.uploaded_by %}
                <a href="{% url 'book:edit_book' book.id %}">{{book.title}}</a>
                {% else %}
                <a href="{% url 'book:view_book' book.id %}">{{book.title}}</a>
                {% endif%}
                <h5> added by {{book.uploaded_by.first_name}}</h5>
                {% if logged_user in book.users_who_like.all %}
                <p>this is one of your favorite</p>
                {% else %}
                <div><a href="{% url 'book:add_favorite' book.id %}">Add to Favorite</a></div>
                {% endif%}
                {% endfor%}
            </div>
        </div>
        <div class="container mt-5">
            <h5>All Favorite Book For me</h5>
            <ul>
                {% for book in logged_user.liked_books.all %}
                <li> {{ book.title }}
                </li>
                {% endfor %}
            </ul>
        </div>

        <!-- Messages -->
        <ul class="container py-5 text-center">
            {% if messages %}
            {% for m in messages %}
            {% if m.tags == 'error' %}
            <div class="alert alert-danger">
                {% else %}
                <div class="alert alert-success">
                    {% endif %}
                    {{ m }}
                </div>
                {% endfor %}
                {% endif %}
        </ul>
    </div>
    <script>
        setTimeout(function () {
            document.querySelectorAll(".alert").forEach(function (alert) {
                alert.classList.add("fade");
                alert.classList.remove("show");
                setTimeout(() => alert.remove(), 500);
            });
        }, 3000);
    </script>
</body>

</html>

favorite_books/book_app/templates/view_book.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>View Book</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">

</head>

<body>
    <div class="container py-4">
        <div class="d-flex justify-content-between align-items-center">
            <h3> Welcome {{logged_user.first_name}}</h3>
            <a href="{% url 'user:logout' %}" class="link-opacity-100">Logout</a>
        </div>

        <div class="row">
            <div class="col-md-6 card">
                <h1> {{book.title}} </h1>
                <p>Added by :{{book.uploaded_by.first_name}} {{book.uploaded_by.Last_name}}</p>
                <p>Added on :{{book.created_at}}</p>
                <p>Last updated on :{{book.updated_at}}</p>
                <p>Description : {{book.desc}} </p>
            </div>
            <div class="col-md-6">
                <h3>User Who Like This Book</h3>
                <ul>
                    {% for user in liked_user %}
                    <p>{{user.first_name}} {{user.last_name}}</p>
                    {% endfor %}
                </ul>
                {% if not logged_user == user %}
                <a href="{% url 'book:add_favorite' book.id %}">Add to Favorite</a>
                {% endif %}
            </div>
        </div>
    </div>
</body>

</html>